# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PlantboxTools
                                 A QGIS plugin
 Outside plant design tools for QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-11
        copyright            : (C) 2025 by Telecom Craft
        email                : admin@telecomcraft.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PlantboxTools class from file PlantboxTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .plantbox_tools import PlantboxTools
    return PlantboxTools(iface)
